[2024-01-04 08:54:13,097] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-01-04T08:54:04.719676+00:00 [queued]>
[2024-01-04 08:54:13,112] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-01-04T08:54:04.719676+00:00 [queued]>
[2024-01-04 08:54:13,112] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-01-04 08:54:13,112] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-01-04 08:54:13,112] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-01-04 08:54:13,130] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-01-04T08:54:04.719676+00:00
[2024-01-04 08:54:13,138] {standard_task_runner.py:52} INFO - Started process 734 to run task
[2024-01-04 08:54:13,142] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting', 'merge_data', '2024-01-04T08:54:04.719676+00:00', '--job-id', '138', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpn44e1fe0', '--error-file', '/tmp/tmpaiqx9nyb']
[2024-01-04 08:54:13,145] {standard_task_runner.py:77} INFO - Job 138: Subtask merge_data
[2024-01-04 08:54:13,199] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting.merge_data 2024-01-04T08:54:04.719676+00:00 [running]> on host bd9da4259c23
[2024-01-04 08:54:13,266] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T08:54:04.719676+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-04T08:54:04.719676+00:00
[2024-01-04 08:54:13,297] {python.py:151} INFO - Done. Returned value was: None
[2024-01-04 08:54:13,308] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting, task_id=merge_data, execution_date=20240104T085404, start_date=20240104T085413, end_date=20240104T085413
[2024-01-04 08:54:13,355] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-01-04 08:54:13,384] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
